### ISSUE TITLE
docker clef 问题

### ISSUE THREAD

**Issue by m1911** [rootial/SwarmDocker#1]
我看你的yml 文件里面没有运行clef  这样也可以？
clef 不是必须要运行的吗

**Comment by rootial** [comment]
clef 不是必须的哦，导出private key的时候参考 https://mp.weixin.qq.com/s/3LTRV5hhZnkVZnF8K46RAQ

**Comment by m1911** [comment]
@rootial 那就是只要机器允许 就可以在一台上面部署N多节点，而不用部署clef 是这样吧
